### ISSUE TITLE
No longer repeats the pullquote in the visible text

### ISSUE THREAD

**Issue by newlocalmedia** [adamdehaven/perfect-pullquotes#1]
I'm guessing you're using a version of the Roger Johansson/Chris Coyier JS solution for pull quotes. All the plugins using this method recently stopped working. The text in the quote disappears from its normal position in the post and only appears within the pull quote.

**Comment by adamdehaven** [comment]
> I'm guessing you're using a version of the Roger Johansson/Chris Coyier JS solution for pull quotes.

@newlocalmedia I'm not sure what that is? This plugin does not utilize Javascript other than with the Visual Editor insertion button.

**Comment by newlocalmedia** [comment]
I've been sorting through some buggy pullquote plugins that use jQuery to duplicate the text enclosed in the shortcode tags as a pullquote without removing or duplicating the tagged content. I assumed yours attempted the same thing in the same way, but it looks like I was wrong about that.

**Comment by adamdehaven** [comment]
FYI: It's not common practice to open an issue reporting malfunctioning code unless you've downloaded and tested the actual code.

**Comment by newlocalmedia** [comment]
Sorry, that wasn't what I was trying to convey. I did download it and test
it, and since it behaved the same way that several others do when they are
not working, I assumed there was a similar problem. I should have looked
further into it first.

On Mon, Apr 11, 2016 at 9:37 PM Adam DeHaven <notifications@github.com>
wrote:

> Closed #1 <https://github.com/adamdehaven/perfect-pullquotes/issues/1>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/adamdehaven/perfect-pullquotes/issues/1#event-623454940>
>
-- 
*Dan Knauss*
newlocalmedia.com
design. build.. sustain...
+1 712 449-8195 ✆ +1 414 212-5628
