### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by Axinet** [adamdehaven/perfect-pullquotes#10]
Link in project description (marked with red arrow) is invalid (returns 404).

![link](https://user-images.githubusercontent.com/393549/37619293-5e8d7e6c-2bb9-11e8-9e58-0297639593e8.PNG)

**Comment by adamdehaven** [comment]
Good catch! Sorry about that... the link has been updated: [Easily add pull quotes to your WordPress posts](https://adamdehaven.com/blog/easily-add-pullquotes-to-your-wordpress-posts-with-my-perfect-pullquotes-plugin/)
