### ISSUE TITLE
Assumes citation is a person

### ISSUE THREAD

**Issue by newlocalmedia** [adamdehaven/perfect-pullquotes#2]
The schema.org attributes assigned to the citation are hard-coded and assume the source will always be a person.

**Comment by adamdehaven** [comment]
The plugin assumes the citation will be from a quoted individual. I would be willing to bet the average user doesn't know what schema.org schemas are, or structured data for that matter. If you need a use beyond that, I'd recommend submitting a pull request to add the functionality.
