### ISSUE TITLE
Add Sharing Options?

### ISSUE THREAD

**Issue by sungkhum** [adamdehaven/perfect-pullquotes#4]
Love the plugin - I would love to see an option to add sharing buttons (for Twitter and Facebook) so that users can easily share the quote. Possible?

**Comment by adamdehaven** [comment]
It's possible, however there are an infinite number of sharing plugins already available. The primary purpose of this plugin is to provide simple, styled pull quotes. While I won't say this will never happen, it's not a likely addition in the near future. 

Thanks for the suggestion though

**Comment by sungkhum** [comment]
Thanks for your quick response! Yes, it is true there are a ton of sharing plugins, but there aren't any currently maintained pullquote sharing plugins that share to Twitter and Facebook that I can find:
https://wordpress.org/plugins/pullquote/
https://wordpress.org/plugins/pushquote/

Some have integrations for Twitter, but not for Facebook:
https://wordpress.org/plugins-wp/wpsso-tweet-a-quote/
https://wordpress.org/plugins-wp/tweetshare-click-to-tweet/

So not trying to be pushy, but I do think it could make your plugin stand-out (and I love the styles you've created for the pullquote which is why I reached out. Again, just a thought - but totally understand time is short. 👍

**Comment by okrg** [comment]
@sungkhum  Curious if you ever found an alternative solution?

**Comment by sungkhum** [comment]
@okrg I ended up paying someone to create a plugin that would do this for me. Happy to send the code to you if you want it. Just let me know.

**Comment by okrg** [comment]
Yes that would be super: rolando.garcia@gmail.com 🙏

**Comment by sungkhum** [comment]
Just shared it with you @okrg
